
#include "jstudio.h"
#include "romassets.h"

#define BG1_TEMPLE_LEFT 4
#define BG1_TEMPLE_RIGHT BG1_TEMPLE_LEFT + 1
#define BG1_BACKDROP BG1_TEMPLE_RIGHT + 1
#define BG1_FLAME1 BG1_BACKDROP + 1
#define BG1_FLAME2 BG1_FLAME1 + 1
#define P1_HB_BODY 14
#define P1_HB_DUCK P1_HB_BODY + 1
#define P1_HB_ATTACK P1_HB_DUCK + 1
#define P2_HB_BODY P1_HB_ATTACK + 1
#define P2_HB_DUCK P2_HB_BODY + 1
#define P2_HB_ATTACK P2_HB_DUCK + 1
#define SCORPION 12
#define KANO SCORPION + 1

#define SCORPION_IDLE_FRAME_COUNT 7
#define SCORPION_WALK_FRAME_COUNT 9
#define KANO_IDLE_FRAME_COUNT 7
#define KANO_WALK_FRAME_COUNT 9