
#include "jstudio.h"
#include "romassets.h"

#define P1_CURSOR 1
#define P2_CURSOR 2
#define BG1_TEMPLE_LEFT 7
#define BG1_TEMPLE_RIGHT BG1_TEMPLE_LEFT + 1
#define BG1_BACKDROP BG1_TEMPLE_RIGHT + 1
#define BG1_FLAME1 BG1_BACKDROP + 1
#define BG1_FLAME2 BG1_FLAME1 + 1
#define P1_HB_BODY 22
#define P1_HB_DUCK P1_HB_BODY + 1
#define P1_HB_ATTACK P1_HB_DUCK + 1
#define P2_HB_BODY P1_HB_ATTACK + 1
#define P2_HB_DUCK P2_HB_BODY + 1
#define P2_HB_ATTACK P2_HB_DUCK + 1
#define SCORPION 15
#define KANO SCORPION + 1
#define CAGE KANO + 1
#define KANG CAGE + 1
#define RAIDEN KANG + 1
#define SUBZERO RAIDEN + 1
#define SONYA SUBZERO + 1

#define SCORPION_IDLE_FRAME_COUNT 7
#define SCORPION_WALK_FRAME_COUNT 9
#define SCORPION_DUCK_FRAME_COUNT 2
#define SCORPION_BLOCK_FRAME_COUNT 2
#define SCORPION_BLOCK_DUCK_FRAME_COUNT 1
#define KANO_IDLE_FRAME_COUNT 7
#define KANO_WALK_FRAME_COUNT 9
#define KANO_DUCK_FRAME_COUNT 2
#define KANO_BLOCK_FRAME_COUNT 2
#define KANO_BLOCK_DUCK_FRAME_COUNT 1
#define CAGE_IDLE_FRAME_COUNT 7
#define CAGE_WALK_FRAME_COUNT 9
#define CAGE_DUCK_FRAME_COUNT 2
#define CAGE_BLOCK_FRAME_COUNT 2
#define CAGE_BLOCK_DUCK_FRAME_COUNT 1
#define KANG_IDLE_FRAME_COUNT 7
#define KANG_WALK_FRAME_COUNT 9
#define KANG_DUCK_FRAME_COUNT 2
#define KANG_BLOCK_FRAME_COUNT 2
#define KANG_BLOCK_DUCK_FRAME_COUNT 1
#define RAIDEN_IDLE_FRAME_COUNT 10
#define RAIDEN_WALK_FRAME_COUNT 9
#define RAIDEN_DUCK_FRAME_COUNT 2
#define RAIDEN_BLOCK_FRAME_COUNT 2
#define RAIDEN_BLOCK_DUCK_FRAME_COUNT 1
#define SUBZERO_IDLE_FRAME_COUNT 12
#define SUBZERO_WALK_FRAME_COUNT 9
#define SUBZERO_DUCK_FRAME_COUNT 2
#define SUBZERO_BLOCK_FRAME_COUNT 2
#define SUBZERO_BLOCK_DUCK_FRAME_COUNT 1
#define SONYA_IDLE_FRAME_COUNT 7
#define SONYA_WALK_FRAME_COUNT 7
#define SONYA_DUCK_FRAME_COUNT 1
#define SONYA_BLOCK_FRAME_COUNT 2
#define SONYA_BLOCK_DUCK_FRAME_COUNT 1